x-superset-image: &superset-image guardiancr.azurecr.io/superset-docker:auth0
x-superset-depends-on: &superset-depends-on []

version: "3.7"
services:
  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    ports:
      - "8080:8088"
    environment:
      - AUTH0_DOMAIN=baz
      - BASE_URL=example.com
      - AUTH0_CLIENTID=raop
      - AUTH0_CLIENT_SECRET=ssss
    depends_on: *superset-depends-on

  # superset-init:
  #   env_file: docker/.env-non-dev
  #   image: *superset-image
  #   container_name: superset_init
  #   command: ["/app/docker/docker-init.sh"]
  #   user: "root"
  #   depends_on: *superset-depends-on

  db:
    env_file: docker/.env-non-dev
    image: postgres:14
    container_name: superset_db
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auditor_circleci
      - POSTGRES_USER=circleci
      - POSTGRES_PASSWORD=C1rcL3


volumes:
  db_home:
    external: false
